// Polaroid Image Structure
export interface PolaroidImage {
  id: string;
  imageUrl: string;
  label: string; // e.g., "Hiking in the alps."
}

// Kindred User Data Structure
export interface KindredUser {
  id: string;
  name: string;
  age: number;
  location: string; // "City, State" format
  gender: string;
  bio: string;
  profileText: string; // Long string for 'Depth' section
  interests: string[]; // Array of at least 3 strings
  imageUrl?: string; // Profile image URL
  polaroidImages?: PolaroidImage[]; // Array of polaroid images with labels
  quizAnswers: {
    [key: string]: string; // Key-value pairs for compatibility quiz answers
  };
}

// Sample User Data - At least 6 fake profiles
export const sampleUserData: KindredUser[] = [
  {
    id: '1',
    name: 'David',
    age: 33,
    location: 'Austin, TX',
    gender: 'Male',
    bio: 'Ceramic artist and weekend hiker. Looking for someone who appreciates slow mornings and deep conversations.',
    profileText: 'My perfect Sunday starts with a long hike through the greenbelt, followed by a few hours in my studio throwing pots. There\'s something meditative about working with clay—the way it responds to your touch, the patience required. In the evening, I love cooking something new from a cookbook I\'ve been meaning to try, usually with a good playlist in the background. I\'m drawn to people who value authenticity over perfection, who can laugh at themselves, and who understand that the best relationships are built on mutual respect and genuine curiosity about each other\'s inner worlds. I believe in showing up fully, in being present, and in creating space for both joy and vulnerability.',
    interests: ['Hiking', 'Ceramics', 'Cooking', 'Indie Films', 'Philosophy'],
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=1200&fit=crop&crop=faces',
    polaroidImages: [
      {
        id: '1',
        imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=800&fit=crop',
        label: 'Hiking in the alps.',
      },
      {
        id: '2',
        imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600&h=800&fit=crop',
        label: 'Ceramics workshop.',
      },
      {
        id: '3',
        imageUrl: 'https://images.unsplash.com/photo-1556910103-2c727e88e5d4?w=600&h=800&fit=crop',
        label: 'Sunday morning cooking.',
      },
      {
        id: '4',
        imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=800&fit=crop',
        label: 'Mountain view.',
      },
    ],
    quizAnswers: {
      'Would you move for love?': 'Maybe, for the right person',
      'How do you handle conflict in relationships?': 'Take time to think, then discuss',
      'What\'s your ideal Friday night?': 'Mix of both, depending on mood',
      'What matters most in a relationship?': 'Emotional connection and shared values',
      'How do you express love?': 'Through quality time and acts of service',
    },
  },
  {
    id: '2',
    name: 'Sarah',
    age: 31,
    location: 'Portland, OR',
    gender: 'Female',
    bio: 'Film enthusiast and aspiring writer. I believe in the power of stories to connect us.',
    profileText: 'I spend most of my free time watching indie films and writing short stories in coffee shops around the city. There\'s something magical about how a well-told story can make you feel less alone in the world. I\'m passionate about hiking—there\'s no better way to clear your head than a long trail with a good podcast. I love cooking, especially trying recipes from different cultures. I\'m looking for someone who values intellectual conversations, who isn\'t afraid of vulnerability, and who understands that love is an active choice you make every day. I believe in growth, in being honest about who you are and who you\'re becoming, and in creating a partnership where both people can flourish.',
    interests: ['Indie Films', 'Hiking', 'Cooking', 'Writing', 'Reading'],
    imageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&h=1200&fit=crop&crop=faces',
    quizAnswers: {
      'Would you move for love?': 'Absolutely',
      'How do you handle conflict in relationships?': 'Address it immediately',
      'What\'s your ideal Friday night?': 'Quiet evening at home',
      'What matters most in a relationship?': 'Intellectual compatibility and emotional support',
      'How do you express love?': 'Through words of affirmation and quality time',
    },
  },
  {
    id: '3',
    name: 'Ben',
    age: 29,
    location: 'Austin, TX',
    gender: 'Male',
    bio: 'Live music lover and philosophy enthusiast. Always up for a good conversation over coffee or wine.',
    profileText: 'I\'m a photographer by trade, but my real passion is live music. There\'s nothing quite like the energy of a small venue, the way music can bring strangers together. I also love philosophy—I\'m always reading something that makes me question my assumptions. Photography is my way of capturing moments that might otherwise be forgotten. I enjoy hiking on weekends and cooking elaborate meals for friends. I\'m looking for someone who can keep up intellectually, who appreciates the arts, and who values authenticity. I believe relationships should be partnerships where both people encourage each other to grow. I\'m not interested in surface-level connections—I want to know what makes you tick, what you\'re passionate about, and what you\'re working toward.',
    interests: ['Live Music', 'Philosophy', 'Photography', 'Hiking', 'Cooking'],
    imageUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&h=1200&fit=crop&crop=faces',
    quizAnswers: {
      'Would you move for love?': 'Maybe, for the right person',
      'How do you handle conflict in relationships?': 'Take time to think, then discuss',
      'What\'s your ideal Friday night?': 'Going out to socialize',
      'What matters most in a relationship?': 'Intellectual connection and shared interests',
      'How do you express love?': 'Through quality time and physical touch',
    },
  },
  {
    id: '4',
    name: 'Emma',
    age: 27,
    location: 'Seattle, WA',
    gender: 'Female',
    bio: 'Yoga instructor and bookworm. I believe in living intentionally and finding joy in the small moments.',
    profileText: 'I teach yoga part-time and work as a librarian, which means I\'m surrounded by stories all day. I love reading—there\'s nothing better than getting lost in a good book with a cup of tea. I practice yoga daily, not just for the physical benefits but for the mental clarity it brings. I\'m passionate about meditation and mindfulness, and I try to bring that awareness into all aspects of my life. I enjoy hiking on weekends, especially in the Pacific Northwest where there\'s always a new trail to explore. I\'m looking for someone who values personal growth, who understands the importance of self-care, and who can appreciate quiet moments as much as adventurous ones. I believe in building a relationship on a foundation of mutual respect, open communication, and shared values.',
    interests: ['Yoga', 'Reading', 'Meditation', 'Hiking', 'Writing'],
    imageUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=800&h=1200&fit=crop&crop=faces',
    quizAnswers: {
      'Would you move for love?': 'Maybe, for the right person',
      'How do you handle conflict in relationships?': 'Take time to think, then discuss',
      'What\'s your ideal Friday night?': 'Quiet evening at home',
      'What matters most in a relationship?': 'Emotional connection and shared values',
      'How do you express love?': 'Through acts of service and quality time',
    },
  },
  {
    id: '5',
    name: 'Marcus',
    age: 35,
    location: 'Brooklyn, NY',
    gender: 'Male',
    bio: 'Chef and travel enthusiast. I believe food brings people together and every meal is an opportunity to create something beautiful.',
    profileText: 'I\'m a chef at a farm-to-table restaurant, which means I spend my days creating dishes that tell a story. I\'m passionate about cooking, obviously, but also about where food comes from and how it connects us to the earth and to each other. I love traveling—I try to visit a new country every year to learn about different cuisines and cultures. When I\'m not in the kitchen, I enjoy reading cookbooks (yes, for fun), going to farmers markets, and trying new restaurants. I\'m also into fitness—I need to balance all that cooking somehow. I\'m looking for someone who appreciates good food, who values experiences over things, and who isn\'t afraid to try new things. I believe in living fully, in being present, and in creating a life filled with both adventure and comfort.',
    interests: ['Cooking', 'Travel', 'Fitness', 'Reading', 'Art'],
    imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&h=1200&fit=crop&crop=faces',
    quizAnswers: {
      'Would you move for love?': 'Absolutely',
      'How do you handle conflict in relationships?': 'Address it immediately',
      'What\'s your ideal Friday night?': 'Going out to socialize',
      'What matters most in a relationship?': 'Shared experiences and mutual support',
      'How do you express love?': 'Through acts of service and quality time',
    },
  },
  {
    id: '6',
    name: 'Olivia',
    age: 28,
    location: 'San Francisco, CA',
    gender: 'Female',
    bio: 'Software engineer by day, artist by night. I love the intersection of technology and creativity.',
    profileText: 'I work as a software engineer, but my real passion is art. I spend my evenings painting, usually while listening to podcasts or audiobooks. I love the way coding and art both require problem-solving and creativity, just in different ways. I\'m into photography—I love capturing the way light changes throughout the day. I enjoy hiking on weekends, especially in the Bay Area where there are so many beautiful trails. I\'m also a big reader, mostly sci-fi and fantasy, and I love discussing books with others. I\'m looking for someone who values both intellectual and creative pursuits, who can appreciate the beauty in everyday moments, and who understands that life is about balance. I believe in being authentic, in pursuing your passions, and in building relationships based on mutual respect and genuine connection.',
    interests: ['Art', 'Photography', 'Reading', 'Hiking', 'Gaming'],
    imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&h=1200&fit=crop&crop=faces',
    quizAnswers: {
      'Would you move for love?': 'Maybe, for the right person',
      'How do you handle conflict in relationships?': 'Take time to think, then discuss',
      'What\'s your ideal Friday night?': 'Mix of both, depending on mood',
      'What matters most in a relationship?': 'Intellectual compatibility and emotional support',
      'How do you express love?': 'Through quality time and acts of service',
    },
  },
  {
    id: '7',
    name: 'James',
    age: 32,
    location: 'Denver, CO',
    gender: 'Male',
    bio: 'Outdoor enthusiast and environmental advocate. I believe in living sustainably and spending as much time in nature as possible.',
    profileText: 'I work in environmental conservation, which aligns perfectly with my love for the outdoors. I spend most weekends hiking, camping, or skiing depending on the season. There\'s something about being in nature that grounds me and reminds me what\'s truly important. I\'m passionate about sustainability—I try to live in a way that minimizes my impact on the planet. I enjoy reading, especially books about nature and environmental issues. I also love cooking, especially with fresh, local ingredients. I\'m looking for someone who shares my values around sustainability and the environment, who loves being outdoors, and who understands that the best relationships are built on shared values and mutual respect. I believe in living intentionally, in being present, and in creating a life that aligns with your values.',
    interests: ['Hiking', 'Camping', 'Reading', 'Cooking', 'Photography'],
    imageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&h=1200&fit=crop&crop=faces',
    quizAnswers: {
      'Would you move for love?': 'No, my roots are here',
      'How do you handle conflict in relationships?': 'Take time to think, then discuss',
      'What\'s your ideal Friday night?': 'Quiet evening at home',
      'What matters most in a relationship?': 'Shared values and emotional connection',
      'How do you express love?': 'Through acts of service and quality time',
    },
  },
  {
    id: '8',
    name: 'Sophia',
    age: 30,
    location: 'Nashville, TN',
    gender: 'Female',
    bio: 'Musician and coffee enthusiast. I believe music is the universal language and coffee is the fuel that makes everything possible.',
    profileText: 'I\'m a musician—I play guitar and sing, and I perform at local venues around Nashville. Music has always been my way of expressing myself and connecting with others. I love the live music scene here, and I spend a lot of time going to shows and supporting other artists. I\'m also really into coffee—I\'ve learned to make a mean pour-over and I love trying new coffee shops. I enjoy reading, especially biographies of musicians and books about creativity. I\'m also into yoga and meditation, which help me stay grounded amidst the chaos of the music industry. I\'m looking for someone who appreciates music and the arts, who values authenticity and creativity, and who understands that relationships require effort and intentionality. I believe in being genuine, in pursuing your passions, and in building connections that are both deep and meaningful.',
    interests: ['Live Music', 'Coffee', 'Yoga', 'Reading', 'Writing'],
    imageUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=800&h=1200&fit=crop&crop=faces',
    quizAnswers: {
      'Would you move for love?': 'Maybe, for the right person',
      'How do you handle conflict in relationships?': 'Address it immediately',
      'What\'s your ideal Friday night?': 'Going out to socialize',
      'What matters most in a relationship?': 'Emotional connection and shared interests',
      'How do you express love?': 'Through words of affirmation and quality time',
    },
  },
  {
    id: '9',
    name: 'Alex',
    age: 34,
    location: 'Portland, OR',
    gender: 'Male',
    bio: 'Outdoor photographer and philosophy student. I find meaning in capturing moments and exploring big questions.',
    profileText: 'I split my time between photography assignments and philosophy courses at the local university. There\'s something beautiful about how both disciplines ask us to look deeper, to see beyond the surface. I love hiking with my camera—some of my best shots come from being in the right place at the right time, usually after a long trek. Cooking is my way of unwinding, and I love experimenting with new recipes. I\'m drawn to people who think deeply, who aren\'t afraid of questions without easy answers, and who value both adventure and reflection. I believe the best relationships are built on intellectual curiosity and shared wonder about the world.',
    interests: ['Photography', 'Philosophy', 'Hiking', 'Cooking', 'Reading'],
    imageUrl: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=800&h=1200&fit=crop&crop=faces',
    quizAnswers: {
      'Would you move for love?': 'Maybe, for the right person',
      'How do you handle conflict in relationships?': 'Take time to think, then discuss',
      'What\'s your ideal Friday night?': 'Mix of both, depending on mood',
      'What matters most in a relationship?': 'Intellectual connection and shared values',
      'How do you express love?': 'Through quality time and acts of service',
    },
  },
  {
    id: '10',
    name: 'Rachel',
    age: 29,
    location: 'Seattle, WA',
    gender: 'Female',
    bio: 'Writer and film buff. I love stories in all their forms—books, movies, and the ones we tell each other.',
    profileText: 'I write for a living, mostly freelance articles and the occasional short story. When I\'m not writing, I\'m usually watching indie films or reading. There\'s something about a well-crafted narrative that never fails to move me. I love hiking on weekends—it helps clear my head and gives me space to think. Cooking is another creative outlet for me, and I love trying recipes from cookbooks I\'ve read about. I\'m looking for someone who appreciates good stories, who values creativity, and who understands that the best conversations happen when you\'re genuinely curious about another person. I believe in authenticity, in showing up as you are, and in building connections that have depth.',
    interests: ['Writing', 'Indie Films', 'Reading', 'Hiking', 'Cooking'],
    imageUrl: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=800&h=1200&fit=crop&crop=faces',
    quizAnswers: {
      'Would you move for love?': 'Absolutely',
      'How do you handle conflict in relationships?': 'Address it immediately',
      'What\'s your ideal Friday night?': 'Quiet evening at home',
      'What matters most in a relationship?': 'Intellectual compatibility and emotional support',
      'How do you express love?': 'Through words of affirmation and quality time',
    },
  },
  {
    id: '11',
    name: 'Michael',
    age: 31,
    location: 'Austin, TX',
    gender: 'Male',
    bio: 'Chef and outdoor enthusiast. I believe good food and nature are two of life\'s greatest pleasures.',
    profileText: 'I run a small farm-to-table restaurant here in Austin, and I\'m passionate about using local, seasonal ingredients. Cooking isn\'t just my job—it\'s how I express creativity and connect with people. When I\'m not in the kitchen, you\'ll find me hiking or camping. There\'s something about being outdoors that inspires my cooking. I love reading cookbooks and food writing, and I\'m always looking for new techniques and flavors to try. I enjoy photography, especially food photography and nature shots. I\'m looking for someone who appreciates good food, who loves adventure, and who values experiences over things. I believe in living fully, in being present, and in creating a life filled with both comfort and excitement.',
    interests: ['Cooking', 'Hiking', 'Reading', 'Photography', 'Camping'],
    imageUrl: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=800&h=1200&fit=crop&crop=faces',
    quizAnswers: {
      'Would you move for love?': 'Maybe, for the right person',
      'How do you handle conflict in relationships?': 'Take time to think, then discuss',
      'What\'s your ideal Friday night?': 'Mix of both, depending on mood',
      'What matters most in a relationship?': 'Shared experiences and mutual support',
      'How do you express love?': 'Through acts of service and quality time',
    },
  },
  {
    id: '12',
    name: 'Lily',
    age: 28,
    location: 'Portland, OR',
    gender: 'Female',
    bio: 'Yoga teacher and wellness advocate. I believe in the power of mindfulness and movement to transform our lives.',
    profileText: 'I teach yoga and lead meditation workshops around Portland. My practice has been transformative for me, and I love sharing that with others. Reading is a huge part of my life—I\'m always learning about wellness, spirituality, and personal growth. I enjoy hiking, especially in the beautiful Pacific Northwest where there\'s always a new trail to explore. Writing is how I process my thoughts and experiences, and I keep a regular journaling practice. I also love cooking, especially healthy, nourishing meals. I\'m looking for someone who values self-care and personal growth, who appreciates quiet moments as much as active ones, and who understands that relationships are about supporting each other\'s journey. I believe in authenticity, in showing up fully, and in building connections that help us grow.',
    interests: ['Yoga', 'Reading', 'Meditation', 'Hiking', 'Writing'],
    imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&h=1200&fit=crop&crop=faces',
    quizAnswers: {
      'Would you move for love?': 'Maybe, for the right person',
      'How do you handle conflict in relationships?': 'Take time to think, then discuss',
      'What\'s your ideal Friday night?': 'Quiet evening at home',
      'What matters most in a relationship?': 'Emotional connection and shared values',
      'How do you express love?': 'Through acts of service and quality time',
    },
  },
  {
    id: '13',
    name: 'Daniel',
    age: 36,
    location: 'San Francisco, CA',
    gender: 'Male',
    bio: 'Artist and photographer. I see beauty in everyday moments and try to capture that in my work.',
    profileText: 'I\'m a visual artist working primarily in photography and mixed media. My work explores the relationship between nature and urban spaces, and I spend a lot of time hiking to find the perfect shot. I love reading about art history and contemporary artists, and I\'m always looking for new inspiration. Cooking is another creative outlet—I love the process of creating something beautiful and delicious. I enjoy reading, especially books about creativity and the creative process. I\'m looking for someone who appreciates art and creativity, who values beauty in everyday life, and who understands that relationships are about supporting each other\'s passions. I believe in authenticity, in pursuing what you love, and in building connections that inspire growth.',
    interests: ['Art', 'Photography', 'Hiking', 'Cooking', 'Reading'],
    imageUrl: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=800&h=1200&fit=crop&crop=faces',
    quizAnswers: {
      'Would you move for love?': 'Maybe, for the right person',
      'How do you handle conflict in relationships?': 'Take time to think, then discuss',
      'What\'s your ideal Friday night?': 'Mix of both, depending on mood',
      'What matters most in a relationship?': 'Intellectual compatibility and emotional support',
      'How do you express love?': 'Through quality time and acts of service',
    },
  },
  {
    id: '14',
    name: 'Maya',
    age: 32,
    location: 'Denver, CO',
    gender: 'Female',
    bio: 'Environmental scientist and outdoor adventurer. I believe in protecting the places we love.',
    profileText: 'I work as an environmental scientist, studying how we can better protect our natural spaces. My work and personal life are deeply connected—I spend most of my free time hiking, camping, and exploring the mountains around Denver. Photography is how I document the places I love, and I\'m always trying to capture the beauty of the natural world. I enjoy reading, especially books about environmental issues and nature writing. Cooking with local, sustainable ingredients is important to me, and I love experimenting with new recipes. I\'m looking for someone who shares my values around sustainability and the environment, who loves being outdoors, and who understands that relationships are built on shared values and mutual respect. I believe in living intentionally, in being present, and in creating a life that aligns with your values.',
    interests: ['Hiking', 'Camping', 'Photography', 'Reading', 'Cooking'],
    imageUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=800&h=1200&fit=crop&crop=faces',
    quizAnswers: {
      'Would you move for love?': 'No, my roots are here',
      'How do you handle conflict in relationships?': 'Take time to think, then discuss',
      'What\'s your ideal Friday night?': 'Quiet evening at home',
      'What matters most in a relationship?': 'Shared values and emotional connection',
      'How do you express love?': 'Through acts of service and quality time',
    },
  },
  {
    id: '15',
    name: 'Chris',
    age: 30,
    location: 'Nashville, TN',
    gender: 'Male',
    bio: 'Musician and coffee aficionado. I believe music connects us and coffee fuels creativity.',
    profileText: 'I\'m a session musician here in Nashville, playing guitar and bass for various artists. Music is my life, and I love the collaborative energy of the music scene here. When I\'m not playing, I\'m usually at a coffee shop, either working on my own music or just enjoying a good pour-over. I\'m passionate about live music—there\'s nothing like the energy of a great show. I enjoy reading, especially books about music and creativity. Writing songs is another way I express myself, and I love the process of crafting lyrics and melodies. I\'m looking for someone who appreciates music and the arts, who values creativity and authenticity, and who understands that relationships are about supporting each other\'s passions. I believe in being genuine, in pursuing what you love, and in building connections that are both deep and meaningful.',
    interests: ['Live Music', 'Coffee', 'Reading', 'Writing', 'Art'],
    imageUrl: 'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=800&h=1200&fit=crop&crop=faces',
    quizAnswers: {
      'Would you move for love?': 'Maybe, for the right person',
      'How do you handle conflict in relationships?': 'Address it immediately',
      'What\'s your ideal Friday night?': 'Going out to socialize',
      'What matters most in a relationship?': 'Emotional connection and shared interests',
      'How do you express love?': 'Through words of affirmation and quality time',
    },
  },
  {
    id: '16',
    name: 'Jessica',
    age: 27,
    location: 'Seattle, WA',
    gender: 'Female',
    bio: 'Film critic and book lover. I believe stories help us understand ourselves and each other.',
    profileText: 'I write film reviews for a local publication and spend most of my free time watching indie films and reading. There\'s something magical about how a well-told story can make you see the world differently. I love hiking, especially in the beautiful Pacific Northwest where there are so many stunning trails. Reading is my escape and my education—I\'m always learning something new. Writing is how I process what I watch and read, and I love the challenge of articulating what makes a story work. I also enjoy cooking, especially trying recipes from cookbooks I\'ve read about. I\'m looking for someone who values intellectual conversations, who appreciates good stories, and who understands that relationships are about growing together. I believe in authenticity, in being curious, and in building connections that have depth.',
    interests: ['Indie Films', 'Reading', 'Writing', 'Hiking', 'Cooking'],
    imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&h=1200&fit=crop&crop=faces',
    quizAnswers: {
      'Would you move for love?': 'Absolutely',
      'How do you handle conflict in relationships?': 'Address it immediately',
      'What\'s your ideal Friday night?': 'Quiet evening at home',
      'What matters most in a relationship?': 'Intellectual compatibility and emotional support',
      'How do you express love?': 'Through words of affirmation and quality time',
    },
  },
  {
    id: '17',
    name: 'Ryan',
    age: 33,
    location: 'Brooklyn, NY',
    gender: 'Male',
    bio: 'Chef and food writer. I believe food is one of the most powerful ways we connect with each other.',
    profileText: 'I\'m a chef at a restaurant in Brooklyn, and I also write about food for various publications. Cooking is my passion—I love the creativity, the technique, and the way food brings people together. I enjoy reading cookbooks and food writing, and I\'m always looking for new inspiration. Travel is important to me—I try to visit a new place every year to learn about different cuisines and cultures. I love reading, especially books about food, travel, and culture. Art is another interest of mine, and I love visiting galleries and museums. I\'m looking for someone who appreciates good food, who values experiences over things, and who understands that relationships are about sharing life\'s pleasures together. I believe in living fully, in being present, and in creating a life filled with both adventure and comfort.',
    interests: ['Cooking', 'Reading', 'Travel', 'Art', 'Writing'],
    imageUrl: 'https://images.unsplash.com/photo-1552374196-c4e7ffc6e126?w=800&h=1200&fit=crop&crop=faces',
    quizAnswers: {
      'Would you move for love?': 'Absolutely',
      'How do you handle conflict in relationships?': 'Address it immediately',
      'What\'s your ideal Friday night?': 'Going out to socialize',
      'What matters most in a relationship?': 'Shared experiences and mutual support',
      'How do you express love?': 'Through acts of service and quality time',
    },
  },
  {
    id: '18',
    name: 'Amanda',
    age: 29,
    location: 'Austin, TX',
    gender: 'Female',
    bio: 'Ceramic artist and nature lover. I find inspiration in the natural world and the creative process.',
    profileText: 'I\'m a ceramic artist with a studio here in Austin. Working with clay is meditative for me—there\'s something about the process that grounds me and helps me stay present. I love hiking, especially in the greenbelt, and I often find inspiration for my work in nature. Cooking is another creative outlet, and I love the process of creating something beautiful and nourishing. I enjoy reading, especially books about art, creativity, and philosophy. I\'m drawn to people who value authenticity, who appreciate the creative process, and who understand that relationships are about supporting each other\'s growth. I believe in showing up fully, in being present, and in creating space for both creativity and connection.',
    interests: ['Ceramics', 'Hiking', 'Cooking', 'Indie Films', 'Philosophy'],
    imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&h=1200&fit=crop&crop=faces',
    polaroidImages: [
      {
        id: '1',
        imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600&h=800&fit=crop',
        label: 'Working with clay.',
      },
      {
        id: '2',
        imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=800&fit=crop',
        label: 'Hiking in the greenbelt.',
      },
      {
        id: '3',
        imageUrl: 'https://images.unsplash.com/photo-1556910103-2c727e88e5d4?w=600&h=800&fit=crop',
        label: 'Sunday morning pottery.',
      },
      {
        id: '4',
        imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&h=800&fit=crop',
        label: 'Cooking with fresh ingredients.',
      },
    ],
    quizAnswers: {
      'Would you move for love?': 'Maybe, for the right person',
      'How do you handle conflict in relationships?': 'Take time to think, then discuss',
      'What\'s your ideal Friday night?': 'Mix of both, depending on mood',
      'What matters most in a relationship?': 'Emotional connection and shared values',
      'How do you express love?': 'Through quality time and acts of service',
    },
  },
  {
    id: '19',
    name: 'Nina',
    age: 30,
    location: 'Portland, OR',
    gender: 'Female',
    bio: 'Film critic and philosophy enthusiast. I love deep conversations about art, life, and everything in between.',
    profileText: 'I write about films for a living, which means I spend a lot of time watching indie films and thinking about what makes a story resonate. Philosophy has always fascinated me—I love exploring big questions about meaning, existence, and how we connect with each other. Hiking is my way of clearing my head and staying grounded. I enjoy cooking, especially trying new recipes that tell a story. I\'m looking for someone who values intellectual curiosity, who appreciates the arts, and who understands that the best relationships are built on shared interests and mutual respect. I believe in being authentic, in pursuing what you love, and in building connections that have depth and meaning.',
    interests: ['Indie Films', 'Philosophy', 'Hiking', 'Cooking', 'Ceramics'],
    imageUrl: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=800&h=1200&fit=crop&crop=faces',
    polaroidImages: [
      {
        id: '1',
        imageUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=600&h=800&fit=crop',
        label: 'Film festival night.',
      },
      {
        id: '2',
        imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=800&fit=crop',
        label: 'Mountain trail thoughts.',
      },
      {
        id: '3',
        imageUrl: 'https://images.unsplash.com/photo-1556910103-2c727e88e5d4?w=600&h=800&fit=crop',
        label: 'Cooking with friends.',
      },
      {
        id: '4',
        imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600&h=800&fit=crop',
        label: 'Ceramics workshop.',
      },
    ],
    quizAnswers: {
      'Would you move for love?': 'Maybe, for the right person',
      'How do you handle conflict in relationships?': 'Take time to think, then discuss',
      'What\'s your ideal Friday night?': 'Quiet evening at home',
      'What matters most in a relationship?': 'Intellectual compatibility and emotional support',
      'How do you express love?': 'Through words of affirmation and quality time',
    },
  },
];

